### ISSUE TITLE
mow4:problemas con instalación services

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#49]

**Comment by rpardines** [comment]
ECD tras lanzar services:

```
TASK [services/kiwi : manage just migrate kiwi] **************************************************************************************************************************************
failed: [ecd1] (item={'components': ['mysql', 'nginx', 'uwsgi'], 'id': 'kws', 'instance': None, 'ip_lan': '192.168.10.18', 'packages': [], 'role': 'kws', 'scope': 'all', 'server': 'ecd1', 'services': ['kws'], 'sufix': ''}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "cmd": [
        "./manage.py",
        "migrate",
        "--database",
        "krill",
        "--noinput",
        "--settings=kiwi.settings.production"
    ],
    "item": {
        "components": [
            "mysql",
            "nginx",
            "uwsgi"
        ],
        "id": "kws",
        "instance": null,
        "ip_lan": "192.168.10.18",
        "packages": [],
        "role": "kws",
        "scope": "all",
        "server": "ecd1",
        "services": [
            "kws"
        ],
        "sufix": ""
    },
    "path": "/opt/kiwi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
    "syspath": [
        "/tmp/ansible_django_manage_payload_g8zvic2z/ansible_django_manage_payload.zip",
        "/usr/lib/python38.zip",
        "/usr/lib/python3.8",
        "/usr/lib/python3.8/lib-dynload",
        "/usr/local/lib/python3.8/dist-packages",
        "/usr/lib/python3/dist-packages"
    ]
}

MSG:

stdout: Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, isp, pbx, rest_framework_tracking, sessions, silk, voip
Running migrations:
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying core.0001_initial... OK
  Applying core.0002_app... OK
  Applying silk.0001_initial... OK
  Applying silk.0002_auto_update_uuid4_id_field... OK
  Applying silk.0003_request_prof_file... OK
  Applying silk.0004_request_prof_file_storage... OK
  Applying silk.0005_increase_request_prof_file_length... OK
  Applying silk.0006_fix_request_prof_file_blank... OK
  Applying silk.0007_sqlquery_identifier... OK
  Applying silk.0008_sqlquery_analysis... OK

:stderr: System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'cpe-isp' isn't unique. You may not be able to reverse all URLs in this namespace
director.ImportRowModifierSetting.row_modifier: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
director.ImportSourceSetting.source: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
director.ImportedRowProperty.row_checksum: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
director.ImportedRowsetRow.rowset_checksum: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Traceback (most recent call last):
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 268, in handle
    emit_post_migrate_signal(
  File "/opt/kiwi/lib/python3.8/site-packages/django/core/management/sql.py", line 42, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/opt/kiwi/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/opt/kiwi/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/kiwi/lib/python3.8/site-packages/django_icinga/signals.py", line 20, in create_hostgroups
    for hostgroup in IcingaHostgroups.objects.filter(hostgroup_object__is_active=1):
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/models/query.py", line 48, in __iter__
    compiler = queryset.query.get_compiler(using=db)
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/models/sql/query.py", line 294, in get_compiler
    connection = connections[using]
  File "/opt/kiwi/lib/python3.8/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/kiwi/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
```

**Comment by Andresphicus** [comment]
Creo que está solventado, cualquier cosa nos decís @rpardines
